# Generated by Django 5.0.6 on 2024-06-20 20:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados', models.JSONField()),
                ('data_gerado', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.CharField(max_length=20)),
            ],
        ),
    ]
